export const categoryOptions = [
  { value: "programming", label: "Программирование" },
  { value: "web-development", label: "Веб-разработка" },
  { value: "mobile-development", label: "Мобильная разработка" },
  { value: "data-science", label: "Data Science" },
  { value: "artificial-intelligence", label: "Искусственный интеллект" },
  { value: "cybersecurity", label: "Кибербезопасность" },
  { value: "design", label: "Дизайн" },
  { value: "marketing", label: "Маркетинг" },
  { value: "business", label: "Бизнес" },
  { value: "language", label: "Языки" },
  { value: "mathematics", label: "Математика" },
  { value: "physics", label: "Физика" },
  { value: "history", label: "История" },
  { value: "psychology", label: "Психология" },
  { value: "finance", label: "Финансы" },
  { value: "education", label: "Образование" },
  { value: "soft-skills", label: "Soft Skills" },
  { value: "health", label: "Здоровье" },
  { value: "music", label: "Музыка" },
  { value: "other", label: "Другое" },
];